Repository globalbrain/sefirot, pull requests merged in 2021-06, with the labels that each got.

#80 fix: emit number only when value is not NaN (#79)
  lib/components/SInputYear.vue
Labels: bug

#82 feat: add disabled option for select and dropdown
  docs/components/inputs/StoryInputDropdownEXDisabledOptions.vue
  docs/components/inputs/StoryInputSelectEXDisabledOptions.vue
  docs/pages/components/inputs-dropdown/index.vue
  docs/pages/components/inputs-select/index.vue
  lib/components/SInputDropdown.vue
  lib/components/SInputSelect.vue
  lib/composables/Dropdown.ts
  test/components/SInputDropdown.spec.ts
  test/components/SInputSelect.spec.ts
Labels: enhancement

#84 fix: make button unclickable if disabled
  lib/components/SCardHeader.vue
Labels: bug

#85 feat(tooltip): add markdown support
  docs/components/tooltips/StoryTooltipEXLongText.vue
  docs/components/tooltips/StoryTooltipShowcase.vue
  docs/pages/components/tooltips/index.vue
  lib/components/SCardHeader.vue
  lib/components/STooltip.vue
  lib/composables/Tooltip.ts
Labels: duplicate

#86 feat: add disabled option for input-year
  lib/components/SInputYear.vue
Labels: enhancement

#87 feat(input-switch): adds disabled option
  docs/pages/components/inputs-switch/index.vue
  lib/components/SInputSwitch.vue
  test/components/SInputSwitch.spec.ts
Labels: enhancement

#88 feat: make header's actions prop refish
  lib/components/SCardHeader.vue
Labels: enhancement

#89 feat(validation): add minValue validation
  lib/validation/rules/index.ts
  lib/validation/rules/minValue.ts
  lib/validation/validators/index.ts
  lib/validation/validators/minValue.ts
  test/validation/validators/minValue.spec.ts
Labels: enhancement
