Repository globalbrain/sefirot, pull requests merged in 2022-10, with the labels that each got.

#151 build: update npm packages
  package.json
  pnpm-lock.yaml
Labels: dependencies

#149 Adjust some related to STable
  lib/components/SDropdownSectionFilter.vue
  lib/components/STable.vue
  lib/components/STableCellAvatars.vue
  lib/components/STableCellPill.vue
  lib/components/STableColumn.vue
  lib/components/STableFooter.vue
  lib/composables/Dropdown.ts
Labels: bug

#152 fix: align vue-tsc with volar internal
  package.json
  pnpm-lock.yaml
Labels: dependencies

#161 fix(table): invalid prop type error thrown on `color` prop (#157)
  lib/components/STableCellPill.vue
Labels: bug

#162 fix(input-number): display value style is broken (#158)
  lib/components/SInputNumber.vue
  lib/components/SInputText.vue
  stories/components/SInputNumber.story.vue
  tests/components/SInputNumber.spec.ts
Labels: enhancement

#170 feat: add custom component cell for STable
  lib/components/STableCell.vue
  lib/composables/Table.ts
Labels: enhancement
